# Generated by Django 4.0.1 on 2022-01-26 19:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 19, 53, 17, 661607, tzinfo=utc)),
        ),
    ]
