version: '3'

services:
  backend:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: auth_service
    volumes:
      - .:/auth_service
      - /db.sqlite3
    ports:
      - "8000:8000"